/**
 * @file libcftext.h
 * @brief Public API header for libcftext – a lightweight C library to detect 
 *        whether a file contains text or binary data.
 *
 * Include this single header to gain access to the detection function,
 * error handling, and version information.
 *
 * @note This library is written in C but fully compatible with C++ through
 *       the use of `extern "C"` linkage.
 *
 * @version 1.0.0
 */

#ifndef LIBCFTEXT_H
#define LIBCFTEXT_H

#ifdef __cplusplus
extern "C" {
#endif

/*===========================================================================*/
/* VERSION MACROS                                                            */
/*===========================================================================*/

/**
 * @def LIBCFTEXT_VERSION_MAJOR
 * @brief Major version number of libcftext.
 *
 * Incremented for incompatible API changes.
 */
#define LIBCFTEXT_VERSION_MAJOR 1

/**
 * @def LIBCFTEXT_VERSION_MINOR
 * @brief Minor version number of libcftext.
 *
 * Incremented for new functionality added in a backward‑compatible manner.
 */
#define LIBCFTEXT_VERSION_MINOR 0

/**
 * @def LIBCFTEXT_VERSION_PATCH
 * @brief Patch version number of libcftext.
 *
 * Incremented for backward‑compatible bug fixes.
 */
#define LIBCFTEXT_VERSION_PATCH 0

/**
 * @def LIBCFTEXT_VERSION
 * @brief Full version string of libcftext.
 *
 * Can be printed or logged to identify the library version at runtime.
 * Format: `"MAJOR.MINOR.PATCH"`.
 */
#define LIBCFTEXT_VERSION "1.0.0"

/*===========================================================================*/
/* ERROR CODE MACROS                                                         */
/*===========================================================================*/

/**
 * @def LIBCFTEXT_OK
 * @brief No error occurred.
 * @see libcftext_get_error()
 */
#define LIBCFTEXT_OK            0

/**
 * @def LIBCFTEXT_ERR_NULL_PTR
 * @brief A required pointer argument (e.g., filename) was NULL.
 * @see is_text_file()
 */
#define LIBCFTEXT_ERR_NULL_PTR  1

/**
 * @def LIBCFTEXT_ERR_OPEN
 * @brief The file could not be opened (missing, permission denied, etc.).
 * @see is_text_file()
 */
#define LIBCFTEXT_ERR_OPEN      2

/**
 * @def LIBCFTEXT_ERR_READ
 * @brief A read error occurred while processing the file.
 * @see is_text_file()
 */
#define LIBCFTEXT_ERR_READ      3

/**
 * @def LIBCFTEXT_ERR_UNKNOWN
 * @brief An unknown error occurred (reserved for future use).
 * @see libcftext_get_error()
 */
#define LIBCFTEXT_ERR_UNKNOWN  99

/*===========================================================================*/
/* PUBLIC FUNCTIONS                                                          */
/*===========================================================================*/

/**
 * @brief Determine whether a file contains text or binary data.
 *
 * The function reads the file in binary mode and applies a heuristic
 * based on the presence of null bytes and the percentage of control
 * characters. A file is considered **text** if:
 * - It contains no null (`0x00`) bytes.
 * - Control characters (other than whitespace: space, tab, CR, LF) make up
 *   less than a configurable threshold (default 10% of bytes read).
 *
 * An empty file is always considered text.
 *
 * @param[in] filename Path to the file to inspect (null‑terminated C string).
 *                     Must not be NULL.
 *
 * @return
 * - **1** : the file is recognized as text.
 * - **0** : the file is recognized as binary.
 * - **-1**: an error occurred. Call libcftext_get_error() immediately to obtain
 *           the error code, and libcftext_strerror() for a human‑readable message.
 *
 * @note **Thread safety**: This function is **not** thread‑safe because it
 *       internally sets a global error state. If used in a multithreaded
 *       environment, protect the call and the subsequent error retrieval with
 *       a mutex, or ensure that only one thread uses the library at a time.
 *
 * @par Example usage:
 * @code
 * int result = is_text_file("document.txt");
 * if (result == -1) {
 *     int err = libcftext_get_error();
 *     fprintf(stderr, "Error: %s\n", libcftext_strerror(err));
 * } else if (result == 1) {
 *     printf("The file is text.\n");
 * } else {
 *     printf("The file is binary.\n");
 * }
 * @endcode
 */
int is_text_file(const char *filename);

/**
 * @brief Retrieve the last error code generated by a library call.
 *
 * The error code is stored in a global (or thread‑local, if implemented)
 * variable and persists until another library function sets it.
 *
 * @return An integer error code:
 *         - LIBCFTEXT_OK (0)
 *         - LIBCFTEXT_ERR_NULL_PTR (1)
 *         - LIBCFTEXT_ERR_OPEN (2)
 *         - LIBCFTEXT_ERR_READ (3)
 *         - LIBCFTEXT_ERR_UNKNOWN (99)
 *
 * @note Always call this function immediately after a library function returns
 *       an error indication; otherwise the error may be overwritten by a
 *       subsequent call.
 */
int libcftext_get_error(void);

/**
 * @brief Set the internal error code (primarily for internal use).
 *
 * Library implementation files (`core.c`, `error.c`) call this to record
 * the reason for a failure. Although it appears in the public header,
 * **user code should not normally call this function** directly; doing so
 * may mask a real error and lead to confusion.
 *
 * @param[in] err One of the LIBCFTEXT_ERR_* codes.
 */
void libcftext_set_error(int err);

/**
 * @brief Convert an error code into a human‑readable static string.
 *
 * @param[in] err An error code as returned by libcftext_get_error().
 *
 * @return A pointer to a constant null‑terminated string describing the
 *         error, e.g. `"Cannot open file"`. The returned string is statically
 *         allocated and must not be freed.
 *
 * @par Example:
 * @code
 * int err = libcftext_get_error();
 * printf("Failure: %s\n", libcftext_strerror(err));
 * @endcode
 */
const char *libcftext_strerror(int err);

/**
 * @brief Get the library version as a static string.
 *
 * This string is useful for display in `--version` output or for logging.
 * The format is the same as the @ref LIBCFTEXT_VERSION macro.
 *
 * @return A pointer to a constant string, e.g. `"1.0.0"`.
 *
 * @see LIBCFTEXT_VERSION
 *
 * @par Example:
 * @code
 * printf("Using libcftext %s\n", libcftext_version());
 * @endcode
 */
const char *libcftext_version(void);

#ifdef __cplusplus
}
#endif

#endif /* LIBCFTEXT_H */